[package]
name = "kecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.*"
petgraph = "0.6.4"
rayon = "1.9.0"

[dev-dependencies]
rand = "0.8.5"
