name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
  miri:
    name: cargo miri
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: "-Zmiri-disable-stacked-borrows"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - run: cargo miri test -- --skip sparse_set
